spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_platform
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
    enabled: false
